# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8422fba9c4e9825bbd91f34694a088d0c02d0b9cfd1914c475b837675cfa3a13e7e37d0feffe3f37e076b7beba1e06dd5b472bf411470807a1037920ac4efee6

test:
  secret_key_base: 00c988e70e0d776d9dadbffbadde07d249fd48fc58a2363e92dacd2d31cd28e3d903112950a2d0bd91c895190dc2141abab26d952dd4e1dbb9479c2ec73f8663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
